### ISSUE TITLE
不要になったロールの全体削除コマンドの実装

### ISSUE THREAD

**Issue by unstoppa61e** [unstoppa61e/grouping-manager-bot#3]

**Comment by unstoppa61e** [comment]
!rm_role 1 などと、引数を取る形にする

**Comment by unstoppa61e** [comment]
誰でも実行できるようにする

**Comment by unstoppa61e** [comment]
誰が実行したかを表示する

**Comment by snara-42** [comment]
こんにちは、bot の動作について質問です。
使われていないロールを削除しようと思い、`+rm` コマンドで `role_0..9` などを削除したのですが、`role_neko` など一部のロールだけは消すことができない模様です。
「snara さんが `role_neko` ロールを削除しました。」と表示されますが、実際には削除されていません。
どんな問題があるかお分かりになりますか？ 

https://github.com/unstoppa61e/grouping-manager-bot/blob/88182f0514fe5f79b7cd42b9c4fa75f9f3fe8878/cogs/role.py#L203
